### ISSUE TITLE
AsyncCommand.ExecuteAsync null check error

### ISSUE THREAD

**Issue by pdinnissen** [StephenCleary/Mvvm.Async#10]
AsyncCommand.ExecuteAsync checks if _canExecute is null, but I believe it means to check if it is not null:

```
public override async Task ExecuteAsync(object parameter)
        {
            Execution = NotifyTask.Create(_executeAsync(parameter));
            if (_canExecute != null)
                base.OnCanExecuteChanged();
            var propertyChanged = PropertyChanged;
            propertyChanged?.Invoke(this, PropertyChangedEventArgsCache.Instance.Get("Execution"));
            propertyChanged?.Invoke(this, PropertyChangedEventArgsCache.Instance.Get("IsExecuting"));
            await Execution.TaskCompleted;
            if (_canExecute != null)
                base.OnCanExecuteChanged();
            PropertyChanged?.Invoke(this, PropertyChangedEventArgsCache.Instance.Get("IsExecuting"));
            await Execution.Task;
        }
```

**Comment by StephenCleary** [comment]
No, the logic is correct. If `_canExecute` is `null`, then the default `CanExecute` logic applies (i.e., `ExecuteAsync` is responsible for raising `CanExecuteChanged`). If `_canExecute` is not `null`, then the user is controlling `CanExecute`, and in that case `ExecuteAsync` does _not_ raise `CanExecuteChanged`.

**Comment by pdinnissen** [comment]
Oh okay, that makes sense.

In that case would you be open to a suggestion to add an optional constructor parameter for 'observeIsExecuting', have the null check be modified to: `_canExecute == null || _observeIsExecuting` and subsequently 'CanExecute' modified to:

```
protected override bool CanExecute(object parameter)
{
      if (_canExecute == null)
           return !IsExecuting;
     return (!_observeIsExecuting || !IsExecuting) && _canExecute(parameter);
}
```

This way the user could have a simple way of making the AsyncCommand blocked from reexecuting without having to explicitly register to the PropertyChanged and then raising OnCanExecuteChanged, but still have the ability to add additional CanExecute conditions.

**Comment by StephenCleary** [comment]
I believe the same capability can be done through a derived class, correct? That would be preferable to further complicating the `AsyncCommand` class.

**Comment by pdinnissen** [comment]
The class is sealed though, so there would alot of reimplementation as opposed to extension.

I'm not sure what's better design, a derived class that is explicit in intention or an additional constructor parameter to determine behaviour.  I'm definitely leaning towards derived.

**Comment by StephenCleary** [comment]
Encapsulation is an option. Generally, encapsulation is superior to inheritance.

**Comment by pdinnissen** [comment]
That's a good point, I would have to reimplement ICommand but that's less work than what I had been doing.  Basically, In the last day I've mashed together your AsyncCommand with a couple of additions (mainly can't execute while IsExecuting and ObserveProperty from Prism's DelegateCommand.). Thanks for taking your time on the issues I posted.  Great to see that your still working on making async easier to use by everyone.

**Comment by StephenCleary** [comment]
The default behavior of `AsyncCommand` is that it can't execute if already executing. I'm not familiar with `ObserveProperty`; what benefit does that give you?

**Comment by pdinnissen** [comment]
But only if CanExecute is null.  If you supply your own delegate then it will not check the IsExecuting flag, that's why I thought the logic was wrong when I initially opened this ticket.

`ObserveProperty` is a handy way of registering which properties of your viewmodel you wish to have raise the CanExecuteChanged call.  Typically, at initialization of the Command itself.  It basically saves you from littering you property setter with Command.CanExecutedChanged calls.  For example:

```
private Employee _currentEmployee;
public Employee CurrentEmployee
{
     get { return _currentEmployee; }
     set { SetProperty(ref _currentEmployee, value); }
}
public MainWindowViewModel()
{
      LoginCommand = new DelegateCommandAsync(CancelCommand.WrapDelegate(Login), CanLogin).ObservesProperty(() => CurrentEmployee);
}
```

instead of:

```
private Employee _currentEmployee;
public Employee CurrentEmployee
{
     get { return _currentEmployee; }
     set { if SetProperty(ref _currentEmployee, value) LoginCommand.OnCanExecuteChanged(); }
}
public MainWindowViewModel()
{
      LoginCommand = new DelegateCommandAsync(CancelCommand.WrapDelegate(Login), CanLogin);
}
```

You can chain the registered properties.  I haven't tried PRISM's other similar ObserveCanExecute.  But ideally I think this all could be taken a step further, where you pass an expression representing a CanExecute delegate, parse the expression for Properties and CalculatedProperties (like your other library) and then you never need worry about forgetting to raise OnCanExecuteChanged, just maintain one CanExecute expression.  I'm not sure what kind of cost that would have, but it definitely would reduce maintenance of Command.
