### ISSUE TITLE
Add constructor overloads with no "parameter" for executeAsync

### ISSUE THREAD

**Issue by cmeeren** [StephenCleary/Mvvm.Async#12]
Most of the time I don't need a parameter for my commands. It would be nice to not have to create my delegates(?) to accept a parameter they'll never use.

I suggest creating a constructor overload:

```c#
// This is the current one
AsyncCommand(Func<object, Task> executeAsync, Func<object, bool> canExecute = null)

// This is my suggested overload
AsyncCommand(Func<Task> executeAsync, Func<bool> canExecute = null)
```

I know Xamarin.Forms has this overload. I haven't tried any other Command implementations yet.

**Comment by StephenCleary** [comment]
Fixed in `1.0.0-eta-03`.
