### ISSUE TITLE
AsyncCommand must be cast to IAsyncCommand or ICommand to access CanExecute and CanExecuteChanged

### ISSUE THREAD

**Issue by cmeeren** [StephenCleary/Mvvm.Async#14]
While unit testing a command defined as `AsyncCommand` instead of `IAsyncCommand` (as you mentioned in #11), I discovered that I could not access `MyAsyncCommand.CanExecute` or `.CanExecuteChanged`; I had to cast it everywhere I wanted to access these properties:

`((IAsyncCommand) MyAsyncCommand).CanExecute`.

Just checking to see if this is a deliberate choice on your part, and if so, what the reasons are.

**Comment by StephenCleary** [comment]
This is deliberate. The `CanExecute` and `CanExecuteChanged` members are intended for use by UI bindings, and not code directly.
