### ISSUE TITLE
Task exceptions not "handled"

### ISSUE THREAD

**Issue by mscottreed** [StephenCleary/Mvvm.Async#17]
I finally have a good repro for this problem.  If you take the code you published for the MSDN article, everything works correctly.  If you then remove the code duplicated by this library and add the prerelease NuGet reference to this library then task based exceptions make it all the way up to unhandled exceptions.
[AsyncCommands3.zip](https://github.com/StephenCleary/Mvvm.Async/files/761501/AsyncCommands3.zip)

Let me know if there are any questions

**Comment by StephenCleary** [comment]
This is a deliberate change in behavior, to make `AsyncCommand` semantics similar to `DelegateCommand`. If you throw an exception from `DelegateCommand`, then it is also a top-level exception.

**Comment by StephenCleary** [comment]
See also: https://github.com/StephenCleary/Mvvm.Async/commit/8e8dae4d6a5db877a85d4fc0ad58a2ec8aab6bc6
