### ISSUE TITLE
Bind to Execution.Result

### ISSUE THREAD

**Issue by metaine** [StephenCleary/Mvvm.Async#18]
Hi, Stephen! Thanks for sharing you thoughts and code on MVVM async.
I tried AsyncCommand pattern in my own project, and a (probably a newb) question arose:
..so, I bind my XAML control to MyAsyncCommand.Execution.Result (where MyAsyncCommand does some time-consuming downloading), and it works almost fine. But! At the time when new command executes, the new Execution object is created, so my bindable control isn't populated with any data until the command completes. And I'd like to have it keeping the old (previously requested) data.

**Comment by StephenCleary** [comment]
Sounds like you're defining `MyAsyncCommand` something like this:

    IAsyncCommand MyAsyncCommand { get { return AsyncCommand.Create(...); } }

which will re-create a new command each time that property is read. If you change it to something like this:

    IAsyncCommand MyAsyncCommand { get; } = AsyncCommand.Create(...);

then it is only set once, and should work as you expect.

If this is not the case, please re-open this issue and post some code that reproduces the issue.
