### ISSUE TITLE
PropertyChangedEventArgsCache does not exist in the current context

### ISSUE THREAD

**Issue by pldeschamps** [StephenCleary/Mvvm.Async#23]
Hello,
In Xamarin.Forms with XAML I want to bind a Geolocation async with a label.
I read there I could use your class NotifyTask:
https://blog.stephencleary.com/2013/01/async-oop-3-properties.html

So I copied the public sealed class NotifyTask in my code but I get the error message described above.
Should I add another class. Can the sealed class NotifyTask be used alone?
Regards

**Comment by StephenCleary** [comment]
`NotifyTask<T>` is part of the [`Nito.Mvvm.Async` library](https://www.nuget.org/packages/Nito.Mvvm.Async). I recommend installing the entire library.

If you want to copy/paste the code instead, you are free to do so, but you'll have to find and include all related types yourself.
