### ISSUE TITLE
AsyncCommand<T> ?

### ISSUE THREAD

**Issue by KMWenyon** [StephenCleary/Mvvm.Async#25]
Stephen,

Can chance you can update the library to include AsyncCommand<T> ?

**Comment by StephenCleary** [comment]
What kind of `<T>` are you looking for? What does the `T` mean?

**Comment by RedX2501** [comment]
I believe he means a way to use CommandParameter in the XAML or calling `Execute([instance of T])`.

**Comment by StephenCleary** [comment]
That's one possibily.
