### ISSUE TITLE
Package release/prerelease status

### ISSUE THREAD

**Issue by agoodwin** [StephenCleary/Mvvm.Async#27]
Hi Stephen,

Firstly, thanks for all of the helpful resources you have produced over the years regarding how to best incorporate asynchronous programming into WPF/MVVM applications. They have been extremely helpful, especially as the combination of WPF, MVVM, and async/await seems to be something that there is no "perfect" solution for.

Next, apologies if creating an issue wasn't the right thing to do here, as all I really have is a quick question regarding the status of this NuGet package:

I am mainly interested in using the NotifyTask type (basically for the same reason as [this question](https://stackoverflow.com/questions/48423750/how-to-invoke-async-operation-on-two-way-bound-combobox-wpf)) but was just wondering if there is a specific reason why you haven't moved this package out of its "prerelease" state yet? Should I take that to mean it's not "prod ready"?

Thanks again,

Adam

**Comment by StephenCleary** [comment]
The `NotifyTask` type is certainly production ready. The `Mvvm.Async` package as a whole is not production ready yet because there's still some work to do on `AsyncCommand` and friends.

**Comment by CZEMacLeod** [comment]
@StephenCleary Any ideas on when this might be done?

**Comment by StephenCleary** [comment]
No. I don't have the bandwidth to work on async commands right now.
