### ISSUE TITLE
Provide interface for NotifyTask

### ISSUE THREAD

**Issue by IbexPeak** [StephenCleary/Mvvm.Async#35]
Hi Stephen,

for unit testing purposes it would be great if NotifyTask (and its generic version) has an interface. This allows mocking of the NotifyTask.

Thanks, Felix

**Comment by StephenCleary** [comment]
It's unusual to mock this type. Can you share what you expect the resulting test would look like?

**Comment by IbexPeak** [comment]
Thanks for your reply, after some additional thinking I came to the conclusion that is doesn't make sense to mock this type.
