### ISSUE TITLE
Why does Nito.Mvvm.CalculatedProperties need to depend on Nito.Mvvm.Core?

### ISSUE THREAD

**Issue by CodingOctocat** [StephenCleary/Mvvm.Async#38]
Is it possible to make Nito.Mvvm.CalculatedProperties independent, if I only use CalculatedProperties then I don't want this package to depend on Nito.Mvvm.Core.

**Comment by StephenCleary** [comment]
CalculatedProperties uses deferred notifications from Core. What would be the benefit of duplicating the code to avoid a tiny dependency?

**Comment by CodingOctocat** [comment]
I first used the CalculatedProperties repository and was only mildly confused by this new repository.

**Comment by StephenCleary** [comment]
Ah, yes. There was a refactoring a few years ago when that dependency was added.
