### ISSUE TITLE
.NET 4.0 Target

### ISSUE THREAD

**Issue by ikondrasovas** [StephenCleary/Mvvm.Async#5]
Hi Stephen,

Is there any implementation of Mvvm.Async targeting .net 4.0?

Curently I am using IAsyncCommand with WPF 4.0 from som implementation I read on your blog about this subject.

However, I am experiencing some ArgumentNullExceptions (Parameter name: task at System.Runtime.CompilerServices.AsyncServices.<ThrowAsync>b__0(Object state)  exceptions when the command execution async method returns right away, like this:

`private async Task SaveAsync(CancellationToken token)
        {
//Do some validation and decide to return prior to continue method execution
            return;
//If OK, do async stuff, returning a task

```
    }`
```

As a workaround, if the code await TaskEx.Delay(1) no exception is thrown.

Thank you,

Igor.

**Comment by StephenCleary** [comment]
The code download for that article contains a bug fix for that issue.

**Comment by ghost** [comment]
Hi @ikondrasovas ,

> Is there any implementation of Mvvm.Async targeting .net 4.0?

Do you have the answer to your question ? Indeed, I'm facing the same need to call Async RelayCommand in .Net 4.0.

Thank you.

**Comment by StephenCleary** [comment]
There has never been a version of Mvvm.Async targeting .NET 4.0.

**Comment by ghost** [comment]
@StephenCleary , thank you for your fast answer. It's very unfortunate for me :-(
